# render.yaml
services:
  - type: web
    name: barakoti-auto-sales
    env: python
    plan: free
    buildCommand: "./build.sh"
    #startCommand: "gunicorn barakotiauto.wsgi:application"
    startCommand: "python manage.py createsu && gunicorn barakotiauto.wsgi:application"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: barakoti-auto-db
          property: connectionString
      - key: SECRET_KEY
        sync: false  # add this manually in dashboard for security
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "barakoti-auto-sales.onrender.com,127.0.0.1,localhost"

databases:
  - name: barakoti-auto-db
