# render.yaml
services:
  - type: web
    name: barakoti-auto-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn barakotiauto.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: barakotiauto-db
          property: connectionString

databases:
  - name: barakotiauto-db
