# Generated by Django 5.1.5 on 2025-07-13 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='date_arrived',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_type', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior')], max_length=32)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventories.inventory')),
            ],
        ),
    ]
